
String textAgentPrompt({String strContexts = '', String strMessages = ''}) {
      // var history = prepareHistory(memo ?? []);
    // var (msgs, ctxs) = buildMsgContext(history);
  var roleAndGoal =
      "# Role and Goal\nYou are an intelligent assistant designed to provide helpful, accurate, and tailored responses to user queries. Your primary objective is to assist users by answering their questions comprehensively and effectively, using a structured approach to information sourcing and response formulation.\n\n";
  var instructions =
      "# Instructions\n1. Information Sourcing:\n   - First, use the LATEST_MESSAGES for relevant information between USER and LOLA messages.\n   - questions given from USER are wrapped in a <USER> tag.\n   - answers given from LOLA are wrapped in a <LOLA> tag.\n   - then, review CONTEXT for additional background or details.\n   - Use your general knowledge as a last resort, clearly indicating when you do so.\n\n2. Response Formulation:\n   - Begin with a concise restatement of the user's query to ensure understanding.\n   - Provide a comprehensive answer, prioritizing using information from LATEST_MESSAGES, then CONTEXT, and finally your general knowledge.\n   - Structure your response using paragraphs, bullet points, or numbered lists as appropriate.\n   - Include relevant examples or analogies to enhance understanding.\n\n3. Accuracy and Transparency:\n   - Clearly attribute information to its source (LATEST_MESSAGES, CONTEXT, or general knowledge).\n   - Express uncertainty when appropriate, using phrases like \"Based on the available information...\" or \"It's possible that...\"\n   - If information is incomplete or unclear, state this explicitly.\n\n4. User-Centric Communication:\n   - Match the user's language, tone, and complexity level.\n   - Anticipate potential follow-up questions and address them proactively.\n   - If clarification is needed, ask specific, targeted questions.\n\n5. Ethical Considerations:\n   - Refuse to assist with harmful, illegal, or unethical requests.\n   - Respect user privacy and maintain confidentiality.\n   - If a topic is sensitive, provide a content warning before delving into details.\n\n6. Continuous Improvement:\n   - At the end of your response, offer 2-3 relevant follow-up questions or related topics the user might be interested in exploring.\n\n";
  var outputInstructions =
      "# OUTPUT INSTRUCTIONS\n- think step-by-step the answer following the Instructions\n- Always translate to the language of the input\n\n";
  var contextStr = "CONTEXT\n----------------------------\n\n$strContexts";
  var latestMessagesStr =
      "LATEST_MESSAGES\n----------------------------\n\n$strMessages";
  // var latestMessagesStr =
  //     "LATEST_MESSAGES\n----------------------------\nUSER: hola como estas Lola?\nASSISTANT: Hola estoy bien, gracias.\nUSER: Se pueden colocar cateteres sin cirugía?\nASSISTANT: Sí, es posible colocar catéteres sin cirugía mediante técnicas de cateterismo guiado por imagen. Estas técnicas utilizan imágenes de rayos X, ecografías o resonancias magnéticas para guiar la colocación del catéter a través de una pequeña incisión en la piel. Esto permite una colocación más precisa y segura del catéter.\nUSER: hola como esta Mexico?\nASSISTANT: México es un país ubicado en la parte sur de América del Norte. Limita al norte con Estados Unidos, al sur y oeste con el océano Pacífico, al sureste con Guatemala, Belice y el Mar Caribe, y al este con el Golfo de México. Es el undécimo país más poblado del mundo y el tercero más grande de América\nUSER: hola como esta Venezuela?\nASSISTANT: Venezuela está pasando por una situación política, económica y social complicada. Hay una crisis humanitaria, con escasez de alimentos y medicinas, altos índices de inflación y una gran polarización política.\nTambién hay problemas de seguridad y violencia en algunas zonas del país. Sin embargo, también hay una gran resistencia y lucha por parte de la población para\nUSER: hola como esta argentina?\nASSISTANT: Argentina es un país ubicado en América del Sur, con una población de aproximadamente 44 millones de habitantes. Su capital es Buenos Aires y su idioma oficial es el español. Es conocida por su rica cultura, su gastronomía, su pasión por el fútbol y sus hermosos paisajes, como las cataratas del Iguazú y la Patagonia\nUSER: hola como esta Puerto Rico?\nASSISTANT: Puerto Rico es un territorio no incorporado de los Estados Unidos ubicado en el Caribe.\nA continuación, te proporciono información sobre cómo está Puerto Rico actualmente:\n- Puerto Rico ha enfrentado desafíos significativos en los últimos años, especialmente después del huracán María en 2017, que causó daños generalizados en la isla.\nUSER: te pregunte algo medico?\nASSISTANT: Basándome en la conversación previa, me preguntaste sobre la posibilidad de colocar catéteres sin cirugía. ¿En qué puedo ayudarte con información médica?.";
  var result = "$roleAndGoal$instructions$outputInstructions$contextStr$latestMessagesStr".trim();
  return result;
}